HOME_DIR = ..
sources_dir = .

project = helloworld
exe_name = helloworld

cpp_sources = main.cpp \
              hello.cpp

pre_build  = pre-build-target
post_build = post-build-target

# dependencies = 

# include_dirs = 

# static_libs = 

# LDFLAGS += 

include $(HOME_DIR)/Makefile.inc

pre-build-target:
	@echo === i all! Now I will build hello world application! ===

post-build-target:
	@echo === Build completed? ===
